### ISSUE TITLE
ESLint: Failed to load config "airbnb" to extend from.

### ISSUE THREAD

**Issue by droderuan** [airbnb/javascript#2233] opened 2020-05-28 16:33 UTC
**expect: Eslint add single quote and add white spaces**
```js 
import React from 'react';

import {Switch} from "react-router-dom";

import Route from "./Route";
```

**error: ESLint: Failed to load config "airbnb" to extend from. Referenced from:**
![image](https://user-images.githubusercontent.com/43659888/83166581-85257180-a0e5-11ea-8988-849215b65b00.png)

**Already did:**
- Deleted node_modules
- run yarn eslint --init
- reloaded vs code

**Directory:**
![image](https://user-images.githubusercontent.com/43659888/83168066-54463c00-a0e7-11ea-8d02-7b37ee5b2842.png)

**ESLint output channel**
```
[Error - 1:12:45 PM] ESLint stack trace:
[Error - 1:12:45 PM] Error: Failed to load config "airbnb" to extend from.
Referenced from: /home/ruan/Documents/Projects/hackingHelp/.eslintrc.js
    at configMissingError (/home/ruan/Documents/Projects/hackingHelp/FRONT-END-Hacking.rio/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/home/ruan/Documents/Projects/hackingHelp/FRONT-END-Hacking.rio/node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23)
    at ConfigArrayFactory._loadExtends (/home/ruan/Documents/Projects/hackingHelp/FRONT-END-Hacking.rio/node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/ruan/Documents/Projects/hackingHelp/FRONT-END-Hacking.rio/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/home/ruan/Documents/Projects/hackingHelp/FRONT-END-Hacking.rio/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/home/ruan/Documents/Projects/hackingHelp/FRONT-END-Hacking.rio/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
    at ConfigArrayFactory.loadInDirectory (/home/ruan/Documents/Projects/hackingHelp/FRONT-END-Hacking.rio/node_modules/eslint/lib/cli-engine/config-array-factory.js:433:16)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/home/ruan/Documents/Projects/hackingHelp/FRONT-END-Hacking.rio/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:328:46)
```
ESLint is working, if I delete last line in file, it add again. When I'd setup in the early of project, was working fine. Stop working after a git pull, eslint config file was in .gitignore.

It already happened to me one time and I was not able to resolve. I'm new with it and sorry if it is a simple question.

**Comment by ljharb** [comment] 2020-05-29 07:14
@droderuan How are you running eslint? Make sure you have nothing globally installed (which is deprecated), and then use `npx eslint` or an `npm run-script`.

**Comment by droderuan** [comment] 2020-05-29 17:15
@ljharb I'm adding eslint first, like development dependency, after I run ```yarn eslint --init```,  I choose the options and when ask to downgrade, I put yes and install everything. Until then, works fine but in the repository I was working, master doesn't have .eslintrc because of .gitignore. After a merge and push, eslintrc was deleted. I removed .eslintrc from .gitignore, installed again in my branch, and master had eslint again. Everything works fine until I did a git push. 
Again, I thought it was because of my mistake in master repo. I deleted node_modules, .eslintrc, removed from package.json, make from the start and still not working. I don't know why it is happening even I make installation from start.

**Comment by ljharb** [comment] 2020-05-29 18:34
(I'm going to close this, since it's not directly related to this config)

Since you're using yarn instead of npm, i'm not sure what debugging steps to suggest; you'll need to make sure you're using eslint *6*, not 7, and that all required peer deps are installed and the versions match. `npm ls` usually tells you this.

**Closed by ljharb** 2020-05-29 18:34 UTC
Labels: question

**Comment by droderuan** [comment] 2020-05-29 19:12
@ljharb after ```npm ls``` it shows a list of missing packages required by **eslint-config-airbnb**. Now I was able to solve the problem by installing them, thanks a lot!

**Comment by jghorton14** [comment] 2021-01-05 00:48
For any future reference, acorrding to [eslint-config-airbnb](url), I needed to run  `npm info "eslint-config-airbnb@latest" peerDependencies` to view the correct versions of each package that `eslint-config-airbnb` needs. I compared that against my already installed packages via `npm ls`

**Comment by ljharb** [comment] 2021-01-05 00:53
@jghorton14 the package readme also tells you how to use `npx install-peerdeps` to automate that process.

**Comment by elhayadi** [comment] 2022-02-20 12:55
I had similar issue on a react app

Failed to load config "airbnb" to extend from.
Referenced from: /usr/src/.eslintrc
and this fixed it!

`npm install -g install-peerdeps`
`install-peerdeps --dev eslint-config-airbnb`

**Comment by dgtllion** [comment] 2022-03-03 06:37
I had this issue with docker. I accidentally added **NODE_ENV=production** (for testing purposes) and forgot it to remove.
By removing it everything worked fine ;)

**Comment by keremcanb** [comment] 2022-03-18 14:40
The cause of my problem was, I forgot an ".eslintrc.js" file one directory up from my project folder. So it was using the wrong ".eslintrc.js" file.

**Comment by pyloolex** [comment] 2022-03-26 11:40
If you face this error in a production build (although you added ESlint in `"devDependencies"`), disable the plugin before building:
```
export DISABLE_ESLINT_PLUGIN=true
yarn build
```

**Comment by SUKANTOBARMAN** [comment] 2022-03-27 05:34
> @ljharb after `npm ls` it shows a list of missing packages required by **eslint-config-airbnb**. Now I was able to solve the problem by installing them, thanks a lot!

How you solve this problem??

**Comment by cweave** [comment] 2022-04-20 14:50
> I had similar issue on a react app
> 
> Failed to load config "airbnb" to extend from. Referenced from: /usr/src/.eslintrc and this fixed it!
> 
> `npm install -g install-peerdeps` `install-peerdeps --dev eslint-config-airbnb`

This worked for me 🎉 

Initially installed `npm i eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react  eslint-plugin-react-hooks@^4.3.0 -g`, but was getting the same issue as OP, so I did `npm install -g install-peerdeps` `install-peerdeps --dev eslint-config-airbnb` plus the below configuration.

Workspace configuration set like this (for Mac):

`
{  
  "eslint.nodePath": "/Users/<USERNAME>/.nvm/versions/node/v14.15.5/lib",
  "eslint.options": {
    "overrideConfigFile": "/Users/<USERNAME>/.eslintrc",
  },
}
`

(I'm using NVM to set my node version, so my pathing will likely look different than yours)

**Comment by abhinav-anshul** [comment] 2022-08-29 11:01
> install-peerdeps --dev eslint-config-airbnb

this works

**Comment by KIBASSA** [comment] 2022-11-10 20:59
I have tried most of the solutions suggested here but nothing works. 
Maybe because my architecture is a bit different. 
I have a client-server architecture that looks like this: 

![clientserver](https://user-images.githubusercontent.com/8443316/201203013-399a6b68-7c3c-4dbf-976b-b7ddeceec1cd.png)

Here is the architecture in details:

![clientserverdetails](https://user-images.githubusercontent.com/8443316/201203058-96dcc281-beeb-4b9d-a7a2-3acf45d8cba9.png)

Client part contains .eslintrc.json but the server part (root folder) does not.

When I run locally, it works fine but when I try to deploy on heroku, I get this error : 

```
[eslint] Failed to load config "airbnb" to extend from.
remote: Referenced from: /tmp/build_b7392388/client/.eslintrc.json
```

Here is package.json from server (root folder): 

```
{
  "proxy": "http://localhost:3001",
  "name": "emoteco_nodejs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "homepage": ".",
  "scripts": {
    "start": "node server/index.js",
    "build": "cd client && npm install && npm run build",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "engines": {
    "node": "14.17.5"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "applicationinsights": "^2.3.0",
    "axios": "^0.27.2",
    "azure-storage": "^2.10.7",
    "express": "^4.17.2",
    "gm": "^1.23.1",
    "image-data-uri": "^2.0.1",
    "jsonwebtoken": "^8.5.1",
    "mongodb": "^4.2.2",
    "multer": "^1.4.5-lts.1",
    "node-cron": "^3.0.0",
    "node-html-to-image": "^3.2.4",
    "nodemailer": "^6.7.7",
    "react-validation": "^3.0.7",
    "validator": "^13.7.0"
  },
  "devDependencies": {
    "sass": "^1.52.1"
  }
}


```

Here is package.json from client (sub folder): 

```
{
  "name": "emotecoapp",
  "version": "2.0.1",
  "private": true,
  "author": "Creative Tim",
  "license": "See license in https://www.creative-tim.com/license",
  "description": "Otis Kit PRO by Creative Tim",
  "homepage": "",
  "bugs": {
    "url": "https://github.com/creativetimofficial/ct-otis-kit-pro/issues"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/creativetimofficial/ct-otis-kit-pro.git"
  },
  "engines": {
    "node": "14 || 15 || 16",
    "npm": ">=6"
  },
  "dependencies": {
    "@emotion/cache": "11.7.1",
    "@emotion/react": "11.9.0",
    "@emotion/styled": "11.8.1",
    "@mui/icons-material": "5.6.2",
    "@mui/material": "5.6.4",
    "@mui/styled-engine": "5.6.1",
    "@testing-library/jest-dom": "5.16.4",
    "@testing-library/react": "13.2.0",
    "@testing-library/user-event": "14.1.1",
    "@types/jest": "^29.2.0",
    "@types/node": "^18.11.7",
    "@types/react": "^18.0.24",
    "@types/react-dom": "^18.0.8",
    "axios": "^1.1.3",
    "chroma-js": "2.4.2",
    "flatpickr": "4.6.13",
    "onnxjs": "^0.1.8",
    "prop-types": "15.8.1",
    "react": "18.1.0",
    "react-copy-to-clipboard": "5.1.0",
    "react-countup": "6.2.0",
    "react-dom": "18.1.0",
    "react-flatpickr": "3.10.11",
    "react-native-pytorch-core": "^0.2.2",
    "react-router-dom": "6.3.0",
    "react-scripts": "5.0.1",
    "react-syntax-highlighter": "15.5.0",
    "react-webcam": "^7.0.1",
    "rellax": "1.12.1",
    "swiper": "7.3.4",
    "typed.js": "2.0.12",
    "typescript": "^4.8.4",
    "uuid": "8.3.2",
    "web-vitals": "2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "eslint": "^8.2.0",
    "eslint-config-airbnb": "19.0.4",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-import": "^2.25.2",
    "eslint-plugin-jsx-a11y": "6.5.1",
    "eslint-plugin-prettier": "4.0.0",
    "eslint-plugin-react": "7.29.4",
    "eslint-plugin-react-hooks": "4.5.0",
    "prettier": "2.6.2"
  }
}

```

Does anyone have a suggestion for my case?

**Comment by ljharb** [comment] 2023-03-15 18:56
@PLQin that's by design; extensions are supposed to be omitted.

**Comment by joneardley1** [comment] 2023-03-20 16:31
I really don't understand any of this but I'd like to if anybody could help
me
