### ISSUE TITLE
Why is there no new release since Oct. 2017 / v.16.1 ?

### ISSUE THREAD

**Issue by sylv3r** [airbnb/javascript#1803] opened 2018-05-06 15:47 UTC
Since React v16 a few changes are required (like adding `componentDidCatch` to `exceptMethods` option of `class-methods-use-this`) which are actually already committed in your rules, but without any release associated.

Are you planning to release these required changes soon ?

**Comment by ljharb** [comment] 2018-05-07 05:32
There's still plenty of React 16 work required in eslint-plugin-react; see https://github.com/yannickcr/eslint-plugin-react/issues/1442.

**Comment by ljharb** [comment] 2018-05-07 05:33
Duplicate of #1800, duplicate of #1759.

**Closed by ljharb** 2018-05-07 05:33 UTC
