### ISSUE TITLE
Remove no-duplicate-imports

### ISSUE THREAD

**Issue by zackargyle** [airbnb/javascript#1195] opened 2016-12-07 17:37 UTC
Hey!

Currently the configs have `es6/no-duplicate-imports` and `import/no-duplicates` which do the exact same thing (check for duplicate paths in module imports). I'd like for `no-duplicate-imports` to be removed because it does not support FlowType imports (but `no-duplicates` does). So currently any time you have need to import a type and a function from the same file you have to disable the rule. These are different import types and cannot be consolidated into a single declaration. Since both rules are doing the same thing, it should be easy to remove the former in favor of the latter.

**Comment by ljharb** [comment] 2016-12-07 18:26
Duplicate of #1054 - https://github.com/airbnb/javascript/issues/1054#issuecomment-244881253 is the relevant comment.

**Comment by zackargyle** [comment] 2016-12-07 18:32
> Since Airbnb doesn't currently use Flow, and my personal thinking is that files should export one thing (meaning the type should be in a separate file, if I understand correctly) - I think for now, this should be an app-level config that disables no-duplicate-imports.

I think this should be revisited. This is an easy win that actually helps AirBnB anyway, since removing extraneous rules is always a good thing. Both do the exact same thing, so there is no benefit in keeping both. By removing `no-duplicate-imports` you lose no functionality but you throw a bone to the large number of people starting to use Flow. There is no downside to this request.

**Closed** 2016-12-12 07:12 UTC
