### ISSUE TITLE
Relative links on http://airbnb.io/javascript/ not resolving 

### ISSUE THREAD

**Issue by kevindavus** [airbnb/javascript#1700] opened 2018-01-16 18:42 UTC
Specifically, the React and css-in-javascript links Result in 
<img width="708" alt="screen shot 2018-01-16 at 1 41 19 pm" src="https://user-images.githubusercontent.com/4150097/35005888-fbeb9db0-fac2-11e7-9f7a-9ef8028ef1b0.png">

**Comment by ljharb** [comment] 2018-01-16 19:36
This is a duplicate of #1468.

**Closed by ljharb** 2018-01-16 19:36 UTC
