### ISSUE TITLE
no-continue rationale

### ISSUE THREAD

**Issue by zakini** [airbnb/javascript#1933] opened 2018-10-09 09:26 UTC
I've just noticed that continue statements are disallowed in this config, but this is not mentioned in the readme. What's the rationale behind including this rule?

**Comment by catcher-in-the-try** [comment] 2018-10-10 09:16
Duplicate of #1103 #966

**Closed as completed** 2018-10-10 13:27 UTC
Labels: question

**Comment by Zakini** [comment] 2018-10-11 12:27
Sorry, I somehow missed those when I searched for no-continue before
