### ISSUE TITLE
upgrade eslint-config-airbnb and eslint-config-airbnb-base to latest versions

### ISSUE THREAD

**Issue by nagkumar** [airbnb/javascript#957] opened 2016-07-20 06:54 UTC
We are seeing this issue while working with latest react.

npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint@^2.9.0 but none was installed.
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-jsx-a11y@^1.2.0 but none was installed.
npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint@^2.9.0 but none was installed.

Can you pl. upgrade these to work with 

  "eslint": "3.1.1",
 "eslint-plugin-import": "^1.11.0",
    "eslint-plugin-react": "^5.2.2",

**Comment by ljharb** [comment] 2016-07-20 06:55
Duplicate of #936.

**Closed by ljharb** 2016-07-20 06:55 UTC
