### ISSUE TITLE
Updating to v18 broke eslint-plugin-react

### ISSUE THREAD

**Issue by Mykybo** [airbnb/javascript#2079] opened 2019-08-23 14:32 UTC
Errors:
```
Definition for rule 'react/state-in-constructor' was not foundeslint(react/state-in-constructor)
Definition for rule 'react/static-property-placement' was not foundeslint(react/static-property-placement)
Definition for rule 'react/jsx-props-no-spreading' was not foundeslint(react/jsx-props-no-spreading)
```

Package json:
```
"eslint": "6.2.1",
"eslint-config-airbnb": "18.0.1",
"eslint-plugin-react": "7.14.3",
```

elsintrc:
`"plugins": ["react", "prettier", "react-hooks"],`

**Comment by ljharb** [comment] 2019-08-23 14:35
This seems related to #2078 and maybe #2077, but closing as a duplicate of #2069

**Closed by ljharb** 2019-08-23 14:35 UTC
