### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by weihongyu12** [airbnb/javascript#2170] opened 2020-02-27 09:49 UTC
Hello, there are more and more projects developed based on TypeScript. Are there any plans to support TypeScript rules?

Although the existing Airbnb rules can support TypeScript, developers need to make some extensions themselves, so it may be easier to create ambiguity in the community.

I think if you plan to support TypeScript rules, you need to be like JavaScript rules. Supports both basic and react versions

Maybe like this:

```javascript
module.exports = {
  // extends: "airbnb-base/typescript"
  extends: "airbnb/typescript"
}
```

**Comment by ljharb** [comment] 2020-02-27 15:28
Duplicate of #1919.

**Closed by ljharb** 2020-02-27 15:28 UTC

**Comment by asterikx** [comment] 2020-05-14 09:52
It a duplicate, yes. But the referenced issue is locked and almost 2 years old. As @weihongyu12 says, TypeScript has gained massive adoption since then.

Is there a reason why you cannot provide a config for Typescript? An official recommendation on which config(s) to use/which rules to override would be helpful to a lot of people (including myself).

**Comment by ljharb** [comment] 2020-05-14 15:00
When Airbnb is ready to do so, this repo surely will.

**Comment by vicasas** [comment] 2023-05-26 22:05
@ljharb I understand that as long as Airbnb does not adopt the use of TypeScript as a fundamental part of the JavaScript ecosystem, this will not be done. But, I wonder, from the community we could open a Pull Request to create a dedicated plugin for TypeScript?

**Comment by ljharb** [comment] 2023-05-27 06:27
@vicasas unfortunately since this is airbnb's guide and eslint plugins, nothing should be here that airbnb doesn't follow.
