### ISSUE TITLE
Should there be a section that addresses switch statements?

### ISSUE THREAD

**Issue by chrisngobanh** [airbnb/javascript#470] opened 2015-08-10 22:06 UTC
Should there be a section that addresses switch statements?

For example: 
If I have two cases that I want to do the same thing, how should I style it?

```
// this?
switch(expression) {
  case 1:
  case 3:
    ...
    break;
  case 2:
    ...
    break;
}

// or this?

switch(expression) {
  case 1: case 3:
    ...
    break;
  case 2:
    ...
    break;
}
```

Should there be a space between `switch` and the opening parentheses?

```
// this?
switch (expression) {
...
}

// or this?
switch(expression) {
...
}
```

Is it okay to put a default at the beginning of the switch statement, or should it always go in the end?

```
// this?
switch(expression) {
  default:
    ...
    break;
  case 1:
    ...
}

// or this?
switch(expression) {
  case 1:
    ...
    break;
  default:
    ...
}
```

Is it okay to leave the last case without a break?
```
// this?
switch(expression) {
  case 1:
    ...
    break;
  case 2:
    ...
}

// or this?
switch(expression) {
  case 1:
    ...
    break;
  case 2:
    ...
    break;
}
```

Should the cases be on the same indent as the switch?

```
// this?
switch(expression) {
case 1:
  ...
  break;
case 2:
  ...
  break;
}

// or this?
switch(expression) {
  case 1:
    ...
    break;
  case 2:
    ...
    break;
}
```

**Comment by udivankin** [comment] 2015-10-02 12:19
Bump.

This would be nice also if you add {"SwitchCase": 1} to eslint rules according to your decision on switch statement indenting.

**Comment by ljharb** [comment] 2015-10-02 15:40
My preference is to ban `switch` statements altogether - but if allowed, styled like so:
```js
switch (condition) {
  case 1:
    …
    break;
  case 2;
    …
    break;
  default:
    …
}
```

Every single case should have a "break" except "default", there must always be a "default" case present, and "default" should always go at the end.

**Comment by macebedo** [comment] 2015-10-02 16:33
Add an alert() on the "default:" if the the user makes an invalid selection.

**Comment by ljharb** [comment] 2015-10-02 17:11
I'm going to assume that's a troll comment, since `alert` freezes the browser and shouldn't ever be used :-)

**Comment by chrisngobanh** [comment] 2015-10-02 17:31
@macebedo Switch statements can be used in places that don't include user input.

**Comment by macebedo** [comment] 2015-10-02 17:39
@ljharb Oh no, I'm not a troll nor anything troll related haha.  Just trying to help. I'm new to this site.
@chrisngobanh Okay I see.

**Comment by ljharb** [comment] 2016-04-20 04:26
Duplicate of #296.

**Closed by ljharb** 2016-04-20 04:26 UTC
