### ISSUE TITLE
Airbnb rules for TS

### ISSUE THREAD

**Issue by LukeSamkharadze** [airbnb/javascript#2417] opened 2021-05-01 07:06 UTC
I want to set up airbnb rules for entirely **TS** codebase and I have spme questions on which **ESlint** rules to extend

I have found this **NPM** package [**ESlint Airbnb Typescript**](https://github.com/iamturns/eslint-config-airbnb-typescript), but as it seems this one is not from the official airbnb, I may be mistaken... I want to know if this is a good rules to extend

Also I want to know if [**ESlint Airbnb Base**](https://www.npmjs.com/package/eslint-config-airbnb-base) is fully compatible with **TS**. And If this official base is enough, then why does [**ESlint Airbnb Typescript**](https://github.com/iamturns/eslint-config-airbnb-typescript) exist?

**Comment by ljharb** [comment] 2021-05-01 14:51
There is no official Airbnb typescript config. To support it, you’d need at least to use the typescript parser and the typescript versions of core rules.

Duplicate of #1919.

**Closed by ljharb** 2021-05-01 14:51 UTC
