### ISSUE TITLE
problem with port

### ISSUE THREAD

**Issue by D3M3NTOS** [airbnb/javascript#1734] opened 2018-02-18 23:44 UTC
My problem
SyntaxError: Unexpected token <
at Object.parse (native)
at Request._callback (/home/bot/site.js:63:16)
at Request.self.callback (/home/bot/node_modules/request/request.js:186:22)
at emitTwo (events.js:87:13)
at Request.emit (events.js:172:7)
at Request. (/home/bot/node_modules/request/request.js:1163:10)
at emitOne (events.js:77:13)
at Request.emit (events.js:169:7)
at IncomingMessage. (/home/bot/node_modules/request/request.js:1085:12)
at IncomingMessage.g (events.js:260:16)
[2018-02-18 23:40:31.050] [TRACE] [default] - Strange error
[2018-02-18 23:40:31.050] [DEBUG] [default] - { [Error: listen EADDRINUSE :::5424]
code: 'EADDRINUSE',
errno: 'EADDRINUSE',
syscall: 'listen',
address: '::',
port: 5424 }
Error: listen EADDRINUSE :::5424
at Object.exports._errnoException (util.js:907:11)
at exports._exceptionWithHostPort (util.js:930:20)
at Server._listen2 (net.js:1253:14)
at listen (net.js:1289:10)
at Server.listen (net.js:1385:5)
at Server.listen.Server.attach (/home/bot/node_modules/socket.io/lib/index.js:237:9)
at null._onTimeout (/home/bot/site.js:618:29)
at Timer.listOnTimeout (timers.js:92:15)

I change port in site.js and problem persists

**Comment by olstenlarck** [comment] 2018-02-18 23:56
Can you give the surrounding code? It seems like ESLint can't parse the code. Are u sure that you included the React preset? _(assuming you are using JSX, based on the error message `SyntaxError: Unexpected token <`...)_

**Comment by ljharb** [comment] 2018-02-19 01:56
I’m not sure what the issue is; but it’s definitely not related to this style guide.

If you can provide more info, we can certainly continue to help you debug, but I’m going to close this in the meantime.

**Closed by ljharb** 2018-02-19 01:56 UTC

**Comment by D3M3NTOS** [comment] 2018-02-19 07:05
"use strict";
var CASEW = 1050;
var LAST_BET = 0;
var MAX_BET = 0;
var HIDEG = false;
var USER = "";
var RANK = 0;
var ROUND = 0;
var HOST = "188.166.89.144:5424";
var SOCKET = null;
var showbets = true;

function todongers(x) {
	if ($("#settings_dongers").is(":checked")) {
		return (x / 1000);
	}
	return x;
}

function todongersb(x) {
	if ($("#settings_dongers").is(":checked")) {
		return (x / 1000).toFixed(3);
	}
	return x;
}
var snapX = 0;
var R = 0.999;
var S = 0.01;
var tf = 0;
var vi = 0;
var animStart = 0;
var isMoving = false;
var LOGR = Math.log(R);
var $CASE = null;
var $BANNER = null;
var $CHATAREA = null;
var SCROLL = true;
var LANG = 1;
var IGNORE = [];
var sounds_rolling = new Audio('/template/sounds/rolling.wav');
sounds_rolling.volume = 0.5;
var sounds_tone = new Audio('/template/sounds/tone.wav');
sounds_tone.volume = 0.75;

**Comment by D3M3NTOS** [comment] 2018-02-19 07:06
this is now.js

**Comment by D3M3NTOS** [comment] 2018-02-19 07:07
and thos os site.js var mysql = require('mysql');
var log4js = require('log4js');
var io = require('socket.io')(8000);
var request = require('request');
var fs = require('fs');
var md5 = require('md5');
var sha256 = require('sha256');
var math = require('mathjs');

log4js.configure({
	appenders: [
		{ type: 'console' },
		{ type: 'file', filename: 'logs/site.log' }
	]
});
var logger = log4js.getLogger();

var pool  = mysql.createPool({
	connectionLimit : 10,
	database: 'csgo',
	host: 'localhost',
	user: 'root',
	password: 'tsk46gdhj36'
});

process.on('uncaughtException', function (err) {
 logger.trace('Strange error');
 logger.debug(err);
});

**Comment by olstenlarck** [comment] 2018-02-19 13:20
@D3M3NTOS don't know, don't make any sense with the given error output.
