### ISSUE TITLE
Not Compatible with the Latest version of eslint

### ISSUE THREAD

**Issue by awaidqureshi** [airbnb/javascript#3020] opened 2024-07-30 16:17 UTC
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: smart-react@1.0.33
npm ERR! Found: eslint@9.8.0
npm ERR! node_modules/eslint
npm ERR! dev eslint@"^9.8.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.32.0 || ^8.2.0" from eslint-config-airbnb@19.0.4
npm ERR! node_modules/eslint-config-airbnb
npm ERR! dev eslint-config-airbnb@"^19.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by ljharb** [comment] 2024-07-30 16:26
Duplicate of #2961.

**Closed by ljharb** 2024-07-30 16:26 UTC
