### ISSUE TITLE
V8.2.0 Init generated file is broken

### ISSUE THREAD

**Issue by dbibbens** [airbnb/javascript#2504] opened 2021-11-11 19:18 UTC
Failed to load plugin 'import' declared in '.eslintrc.js » eslint-config-airbnb » /Users/db/winering/core-web/node_modules/eslint-config-airbnb-base/index.js » /Users/db/winering/core-web/node_modules/eslint-config-airbnb-base/rules/imports.js': Invalid URL: eslintrc.cjs

running node `v16.13.0`
running npm `8.1.0`

```
"eslint": "^8.2.0",
"eslint-config-airbnb": "^19.0.0",
"eslint-plugin-import": "^2.25.3",
"eslint-plugin-jsx-a11y": "^6.5.1",
"eslint-plugin-react": "^7.27.0",
"eslint-plugin-react-hooks": "^4.3.0",
```

```
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    'plugin:react/recommended',
    'airbnb',
  ],
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 13,
    sourceType: 'module',
  },
  plugins: [
    'react',
  ],
  rules: {
  },
};
```

**Comment by ljharb** [comment] 2021-11-11 20:08
Where is eslintrc.cjs coming from?

**Comment by dbibbens** [comment] 2021-11-11 20:58
@ljharb root folder of the project.

im running atom `1.58.0` with linter-eslint `9.0.0` (https://github.com/AtomLinter/linter-eslint)

**Comment by dbibbens** [comment] 2021-11-12 03:44
Little update, after removing and single installing and dealing with each plugin got it working again with the following:

Definitely an issue with `eslint-config-airbnb` plugin for eslint since V8

```
"eslint": "8.2.0",
"eslint-import-resolver-alias": "^1.1.2",
"eslint-plugin-arca": "^0.13.3",
"eslint-plugin-jsx-a11y": "^6.5.1",
"eslint-plugin-react": "^7.27.0",
```
- my eslint config file
[eslintrc-react.txt](https://github.com/airbnb/javascript/files/7524718/eslintrc-react.txt)

**Comment by ljharb** [comment] 2021-11-13 16:43
Does this happen on the command line, or only in vscode? If it's working on the command line, it's a problem with vscode, vscode-eslint, or your vscode configuration.

**Comment by dbibbens** [comment] 2021-11-13 16:45
this might be the same thing with linter-eslint atom package

**Comment by ljharb** [comment] 2021-11-13 16:47
Indeed, it might - i didn't know anyone was still using atom. Does the error happen on the command line?

**Comment by dbibbens** [comment] 2021-11-13 16:50
i like using atom, havent made the switch over to vscode yet. 
i didnt run it command line, im up and running.

**Comment by ljharb** [comment] 2021-11-13 16:52
I'm going to close this for now then; if you encounter the problem in the command line, then I'll be happy to reopen.

**Closed by ljharb** 2021-11-13 16:52 UTC

**Comment by alexrudd2** [comment] 2021-11-15 16:41
I ran into this problem also with Atom, but not on the command line.  See https://github.com/eslint/eslint/issues/14137 for a hint; I think `eslint` considers that a module is being used.

The fix for me was to change `.eslintrc.js` to `.eslintrc.json`.

**Comment by ljharb** [comment] 2021-11-15 16:50
If perhaps the issue is caused by using type: module, i would strongly encourage you to never use that. ESM files should be .mjs, and tooling and users expect .js files to be CJS.

**Comment by alexrudd2** [comment] 2021-11-15 17:45
@ljharb Thanks for the reply.  I misunderstood the problem, and what appeared to work did not in fact persist after an Atom restart.  My `package.json` does not have `type: module`, it's just vanilla JS and we only use Node to install local packages such as `eslint`.  I neither work with nor understand ESM modules, sorry :)

My guess is that the way the `imports` plugin is imported changes some parser (?) to expect modules (?).
https://github.com/airbnb/javascript/blob/d8cb404da74c302506f91e5928f30cc75109e74d/packages/eslint-config-airbnb-base/rules/imports.js#L1-L11

So my new workaround is to just disable those rules in `index.js`
```
module.exports = {
  extends: [
    './rules/best-practices',
    './rules/errors',
    './rules/node',
    './rules/style',
    './rules/variables',
    './rules/es6',
    // './rules/imports',
    './rules/strict',
  ].map(require.resolve),
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  rules: {},
};
```

Additionally, this bug seems related: https://github.com/AtomLinter/linter-eslint/issues/1448
