### ISSUE TITLE
Linting not working in a non-react project

### ISSUE THREAD

**Issue by perrin4869** [airbnb/javascript#799] opened 2016-03-27 07:56 UTC
Just tried using this library on a non react project, and I got the following error:

```
$ eslint index.js                                                                                                                                                    

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-react is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-react@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

This is despite the fact that my `.eslintrc` reads: `"extends": "airbnb/base"`. In my other react related projects, however, the library works like charm.

Library was installed using: `npm install --save-dev eslint-config-airbnb eslint`

Thanks!

PS: Since react projects are a subset of all javascript projects, I think that the default `"extends": "airbnb"` should lint the general javascript project, and maybe have `"extends": "airbnb/react"` support the subset of projects that use react.

**Comment by ljharb** [comment] 2016-03-27 07:57
Due to the way dependencies work, everyone currently needs `eslint-plugin-react` whether or not you have a react project.

This is a duplicate of #751.

**Closed by ljharb** 2016-03-27 07:57 UTC

**Comment by perrin4869** [comment] 2016-03-27 07:59
I see! Thanks, should have looked into it some more :)
