### ISSUE TITLE
`defaultProps` is deprecated for functional components

### ISSUE THREAD

**Issue by sylee957** [airbnb/javascript#2890] opened 2024-01-27 20:47 UTC
I see that the style guide 'recommends' default props for optional props,, even for functional components

https://github.com/airbnb/javascript/tree/master/react#props

> Always define explicit defaultProps for all non-required props.

https://github.com/airbnb/javascript/blob/11ab37144b7f846f04f64a29b5beb6e00d74e84b/packages/eslint-config-airbnb/rules/react.js#L392-L394

However, after watching some discussion, I think that they decided to officially deprecate default props

https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-defaultprops-on-function-components

https://www.youtube.com/watch?v=fnQusZt49_Y

If it is the case that default props are deprecated for react future,
I think that you may have to change that style guide and eslint rules.

**Comment by ljharb** [comment] 2024-01-27 20:58
That decision isn't relevant until they've implemented it, which they haven't yet.

Duplicate of #1702

**Closed by ljharb** 2024-01-27 20:58 UTC
