### ISSUE TITLE
Unable install eslint-config-airbnb due to semver.

### ISSUE THREAD

**Issue by kuu** [airbnb/javascript#745] opened 2016-02-21 06:44 UTC
```
$ npm install eslint-config-airbnb
npm ERR! peerinvalid Peer eslint-config-airbnb@5.0.1 wants eslint-plugin-react@^3.16.1
```
My environment is:
* node: 4.3.1
* eslint: 2.2.0
* eslint-plugin-react: 4.0.0

**Comment by ljharb** [comment] 2016-02-21 06:52
`eslint-config-airbnb` is not yet compatible with eslint v2.x (or eslint-plugin-react v4).

Closing as a duplicate of #730.

**Closed by ljharb** 2016-02-21 06:52 UTC
