### ISSUE TITLE
upgrade eslint-plugin-import to 2.0.0

### ISSUE THREAD

**Issue by graingert** [airbnb/javascript#1107] opened 2016-10-05 10:49 UTC

**Comment by ljharb** [comment] 2016-10-05 15:54
Duplicate of #1101, #1104.

**Closed by ljharb** 2016-10-05 15:54 UTC

**Comment by graingert** [comment] 2016-10-05 20:06
@ljharb I had a comment on this PR a while ago... where did it go?

**Comment by ljharb** [comment] 2016-10-05 20:23
@graingert i'm not sure - I see your comments on #1108 but not any here (except the one you deleted which was asking about it)

**Comment by graingert** [comment] 2016-10-05 20:38
Yep, I saw it too. Hence deleting my comment #sleepy

**Comment by FredyC** [comment] 2016-10-12 12:07
Just little note here. It might be good idea to actually leave at least one *issue* open with this upgrade. I've almost created one issue by myself then I got idea to check out PRs. Unfortunately not everyone gets that idea and duplicate issues gets created. Obviously it's not solved, so closing all related issues doesn't seem right. Up to you, just want to save you some work of closing duplicates :)

**Comment by ljharb** [comment] 2016-11-07 07:00
`eslint-config-airbnb` `v13.0.0` is now released.
