### ISSUE TITLE
[ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning

### ISSUE THREAD

**Issue by evheniy** [airbnb/javascript#1846] opened 2018-06-28 07:36 UTC
Hi

From Yesterday updates I see warning:

[ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "node_modules/eslint-config-airbnb-base/index.js")

**Comment by ljharb** [comment] 2018-06-28 07:38
That means you're using eslint 5, which airbnb's config is not compatible with yet, which means `npm ls` is exiting nonzero, which means you have an invalid dep graph.

Duplicate of #1845; please see #1834.

**Closed by ljharb** 2018-06-28 07:38 UTC
