### ISSUE TITLE
ESlint config errors with eslint v2

### ISSUE THREAD

**Issue by gcallaghan** [airbnb/javascript#728] opened 2016-02-12 16:55 UTC
```
  1:1  error  Rule 'no-empty-label' was removed and replaced by: no-labels                 no-empty-label
  1:1  error  Rule 'space-before-keywords' was removed and replaced by: keyword-spacing    space-before-keywords
  1:1  error  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  1:1  error  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
```

**Comment by ljharb** [comment] 2016-02-12 16:57
Thanks - the latest version is 1.10.3. If you're referring to 2.0.0-rc1, release candidates don't count :-) We'll be updating the rules after v2 is actually released (and we're not recommending its use until then)

**Comment by gcallaghan** [comment] 2016-02-12 17:14
Ooops! sorry, my update script was too aggressive! Thanks for the quick response.

**Comment by ljharb** [comment] 2016-02-12 18:10
np, thanks for the heads up about what to look for when it comes time!

**Comment by ljharb** [comment] 2016-02-12 18:48
and just a few minutes later, https://twitter.com/geteslint/status/698208923560472576

**Comment by ljharb** [comment] 2016-02-12 19:27
Closing as a dupe of #711

**Closed by ljharb** 2016-02-12 19:27 UTC

**Comment by hshoff** [comment] 2016-02-12 20:06
Errors fixed in https://github.com/airbnb/javascript/pull/730
